import json
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

"""Convert a dataset dict (as returned by any generate_*_dataset function in
dataset.py) into a self-documenting NetCDF file: every variable carries a
`description` attribute explaining what it is, and the run's `metadata` dict
is carried over as global attributes (plus a full JSON copy) -- so opening
the file (`xr.open_dataset(path)`, or `ncdump -h`) tells you what you're
looking at without cross-referencing this codebase.

Every dataset gets at least:
    X(sample, input_feature)   -- the training ensemble's inputs (noise-free)
    Y(sample, output_feature)  -- the training ensemble's outputs (noise-free)
    x_true(input_feature)      -- one extra sampled row, held out of the
                                   ensemble: the input a calibration exercise
                                   is trying to recover
    y_true(output_feature)     -- the generating process applied to x_true,
                                   with observation noise/structural bias --
                                   the single "real" observation a
                                   calibration exercise tries to match
which is already a plain (sample x feature) table -- `ds["Y"].to_pandas()` /
`ds.to_dataframe()` gives you rows-are-samples, columns-are-outputs directly.

Everything else in the dict (coefficients, pairs/triplets, sensitivity
indices, ...) is carried over as additional variables, named after their
dict key (nested dicts, e.g. a structural-regime dataset's
`{"regime_1": {...}, "regime_2": {...}}` coefficients/x_true/y_true, are
flattened to "regime_1__coefficients" etc.) -- so this works unmodified on
any dataset dict this repo produces, not just the plain single-generator ones.
"""

_KNOWN_DESCRIPTIONS = {
    "X": "Training-ensemble inputs: for the static generators, sampled parameters (iid "
         "Uniform(-1, 1)); for the ODE/Lorenz-96 generators, sampled initial conditions. Noise-free.",
    "Y": "Training-ensemble outputs: the generating process applied exactly to X, with no "
         "observation error added. Noise-free -- this is the simulator/model output, not "
         "an observation.",
    "x_true": "One extra sampled row, held out of the training ensemble: the input a "
              "calibration exercise is trying to recover.",
    "y_true": "The generating process applied to x_true, with observation noise (noise_std) "
              "and, on structural_idx outputs, a constant structural bias "
              "(structural_error_level) added -- the single real-world-like observation a "
              "calibration exercise tries to match. Not part of the training ensemble.",
    "structural_bias": "Constant bias added to y_true on structural_idx outputs "
                        "(structural_error_level * that output's std within the training "
                        "ensemble Y); zero elsewhere.",
    "paras_to_vary": "Indices of inputs/states marked 'sensitive' -- their coefficients were "
                     "amplified by sensitivity_multiplier.",
    "outputs_to_vary": "Indices of output columns whose driving coefficients were amplified.",
    "regime_label": "Which of two pooled parameter sets generated this row (0/1). Diagnostic "
                     "only -- a real calibration exercise would not have access to this.",
    "param_group_id": "Which block-diagonal sensitivity group each input belongs to (structure="
                       "'blocks'); that group's params are the (near-)exclusive drivers of the "
                       "matching output_group_id outputs.",
    "param_group_membership": "(input_feature, group) 0/1: whether each input belongs to each "
                               "sensitivity group (structure='overlapping_blocks') -- unlike "
                               "param_group_id, a param may belong to more than one group, driving "
                               "more than one output_group_id block of outputs.",
    "output_group_id": "Which block-diagonal sensitivity group each output belongs to (structure="
                        "'blocks'); driven (near-)exclusively by the matching param_group_id params.",
    "output_model_label": "Which model block (0, 1, ...) each output column came from, for a "
                           "generate_conflicting_truth_dataset output -- model i's outputs are "
                           "generated by a different process than model j's, sharing only the "
                           "parameter space.",
    "cross_model_mismatch": "(n_models, n_models): entry [i, j] is the normalized RMS gap between "
                             "model i's true observation and what model i would predict at model "
                             "j's true input. ~0 on the diagonal; large off-diagonal entries are the "
                             "signature of no single input satisfying every model's observation.",
    "pairs": "Parameter/state index pairs (i, j) whose product x_i * x_j has an interaction "
             "coefficient; sensitive pairs (built from paras_to_vary) are listed first.",
    "triplets": "Parameter/state index triplets (i, j, l) whose product has an interaction "
                "coefficient; sensitive triplets are listed first.",
    "A": "ODE dynamics matrix A in dx/dt = A x -- the parameter a calibration method tries "
         "to recover.",
    "forcing": "Lorenz-96 per-state forcing F_i in "
               "dx_i/dt = (x_(i+1) - x_(i-2)) * x_(i-1) - x_i + F_i.",
    "coefficients": "Coefficient matrix B (input x output) such that Y = X @ B.",
    "coefficients_linear": "Linear-term (x_i) coefficient matrix (input x output).",
    "coefficients_quad": "Quadratic-term (x_i^2) coefficient matrix (input x output).",
    "coefficients_cubic": "Cubic-term (x_i^3) coefficient matrix (input x output).",
    "coefficients_pairs": "Pairwise interaction coefficients (pair x output), matching `pairs`.",
    "coefficients_triplets": "Triplet interaction coefficients (triplet x output), matching `triplets`.",
}


def _describe(key):
    base_key = key.split("__")[-1]
    return _KNOWN_DESCRIPTIONS.get(base_key, f"Model array '{key}' (see metadata for the generator that produced it).")


def _json_safe(value):
    """netCDF global attrs can only hold strings/numbers/non-empty 1-D arrays of
    those (no bools, no None, no empty arrays) -- coerce or JSON-encode anything
    else (nested dicts/lists of mixed type)."""
    if isinstance(value, bool):
        return int(value)
    if value is None:
        return "null"
    if isinstance(value, (str, int, float, np.integer, np.floating)):
        return value
    if (isinstance(value, (list, tuple)) and len(value) > 0
            and all(isinstance(v, (int, float, np.integer, np.floating)) and not isinstance(v, bool) for v in value)):
        return list(value)
    return json.dumps(value)


def to_xarray(dataset):
    """Builds the xarray.Dataset described in the module docstring from a
    dataset dict. Does not write anything to disk -- see save_dataset_netcdf."""
    X, Y = dataset["X"], dataset["Y"]
    n_samples, n_inputs = X.shape
    n_outputs = Y.shape[1]
    meta = dataset.get("metadata", {})

    data_vars = {
        "X": (("sample", "input_feature"), X),
        "Y": (("sample", "output_feature"), Y),
    }

    # ODE/Lorenz-96 datasets: Y (and y_true) are time-major flattened (state
    # fastest-varying). Add (sample, time, state) / (time, state) views too,
    # with a real `time` coordinate -- more natural than the flat feature axis.
    if "n_states" in meta and "t_eval" in meta:
        n_states = meta["n_states"]
        t_eval = np.asarray(meta["t_eval"])
        n_times = len(t_eval)
        data_vars["Y_by_time"] = (
            ("sample", "time", "state"), Y.reshape(n_samples, n_times, n_states),
        )
        y_true = dataset.get("y_true")
        if isinstance(y_true, np.ndarray):
            data_vars["y_true_by_time"] = (
                ("time", "state"), np.asarray(y_true).reshape(n_times, n_states),
            )

    for key, value in dataset.items():
        if key in ("X", "Y", "metadata"):
            continue
        _add_variable(data_vars, key, value, n_samples, n_inputs, n_outputs)

    coords = {}
    if "n_states" in meta and "t_eval" in meta:
        coords["time"] = np.asarray(meta["t_eval"])

    ds = xr.Dataset(data_vars, coords=coords)

    for name in ds.data_vars:
        ds[name].attrs["description"] = _describe(name)
    if "Y_by_time" in ds:
        ds["Y_by_time"].attrs["description"] = (
            ds["Y"].attrs["description"] + " Reshaped to (sample, time, state); "
            "state varies fastest within Y's flattened output_feature axis."
        )
    if "y_true_by_time" in ds:
        ds["y_true_by_time"].attrs["description"] = (
            ds["y_true"].attrs["description"] + " Reshaped to (time, state)."
        )

    ds.attrs["summary"] = (
        f"Synthetic parameter-estimation dataset generated by data_generator_funs "
        f"(model={meta.get('model', 'unknown')}). X/Y = noise-free training ensemble, "
        f"x_true/y_true = the single held-out true input and its noisy/biased observation. "
        f"See each variable's 'description' attribute."
    )
    for key, value in meta.items():
        ds.attrs[key] = _json_safe(value)
    ds.attrs["metadata_json"] = json.dumps(meta)

    return ds


def _add_variable(data_vars, key, value, n_samples, n_inputs, n_outputs, prefix=""):
    name = f"{prefix}{key}"
    if isinstance(value, dict):
        if len(value) == 1 and key in value:
            # collapses the linear/exponential-style {"coefficients": B} wrapper so it
            # doesn't produce a redundant "coefficients__coefficients" variable name
            _add_variable(data_vars, key, value[key], n_samples, n_inputs, n_outputs, prefix=prefix)
            return
        for sub_key, sub_value in value.items():
            _add_variable(data_vars, sub_key, sub_value, n_samples, n_inputs, n_outputs, prefix=f"{name}__")
        return

    arr = np.asarray(value)
    if arr.ndim == 0:
        data_vars[name] = ((), arr)
    elif arr.ndim == 1:
        if arr.shape[0] == n_samples:
            dim = "sample"
        elif arr.shape[0] == n_outputs:
            dim = "output_feature"
        elif arr.shape[0] == n_inputs:
            dim = "input_feature"
        else:
            dim = f"{name}_index"
        data_vars[name] = ((dim,), arr)
    elif arr.ndim == 2:
        row_dim = "input_feature" if arr.shape[0] == n_inputs else f"{name}_row"
        col_dim = "output_feature" if arr.shape[-1] == n_outputs else f"{name}_col"
        data_vars[name] = ((row_dim, col_dim), arr)
    else:
        dims = tuple(f"{name}_dim{i}" for i in range(arr.ndim))
        data_vars[name] = (dims, arr)


def save_dataset_netcdf(dataset, path):
    """Writes `to_xarray(dataset)` to a NetCDF file at `path`."""
    ds = to_xarray(dataset)
    ds.to_netcdf(path)
    return ds


def save_dataset_folder(dataset, out_dir, filename_base=None):
    """Writes one dataset into its own folder: out_dir/<filename_base>/, containing
    <filename_base>.nc (everything `save_dataset_netcdf` writes) plus X.csv, Y.csv,
    x_true.csv and y_true.csv. X/Y are the (sample x feature) training ensemble,
    columns named x0..x{n_params-1} / y0..y{n_outputs-1}. x_true/y_true are the single
    held-out row, written one value per line with those same names as the index
    (matching the ",0"-header single-column CSV format used elsewhere for obs tables).

    filename_base defaults to `default_nc_filename(dataset)` with the .nc suffix
    stripped, so the folder name matches what the .nc file would otherwise be
    called.
    """
    if filename_base is None:
        filename_base = Path(default_nc_filename(dataset)).stem

    folder = Path(out_dir) / filename_base
    folder.mkdir(parents=True, exist_ok=True)

    ds = save_dataset_netcdf(dataset, folder / f"{filename_base}.nc")

    X, Y = dataset["X"], dataset["Y"]
    x_cols = [f"x{i}" for i in range(X.shape[1])]
    y_cols = [f"y{i}" for i in range(Y.shape[1])]
    pd.DataFrame(X, columns=x_cols).to_csv(folder / "X.csv", index=True, index_label="sample")
    pd.DataFrame(Y, columns=y_cols).to_csv(folder / "Y.csv", index=True, index_label="sample")

    x_true, y_true = dataset.get("x_true"), dataset.get("y_true")
    if isinstance(x_true, np.ndarray):
        pd.Series(x_true, index=x_cols).to_csv(folder / "x_true.csv")
    if isinstance(y_true, np.ndarray):
        pd.Series(y_true, index=y_cols).to_csv(folder / "y_true.csv")

    return ds


def load_linear_dataset(path):
    """Loads a dataset written by generate_linear_dataset(..., nc_path=...) (or
    generate_exponential_dataset, same shape): `path` can be either the folder
    save_dataset_folder wrote (the first .nc file found inside it is used) or a
    .nc file directly. Returns a dict with X, Y, x_true, y_true, coefficients as
    plain numpy arrays.
    """
    path = Path(path)
    if path.is_dir():
        nc_files = sorted(path.glob("*.nc"))
        if not nc_files:
            raise FileNotFoundError(f"no .nc file found in {path}")
        path = nc_files[0]

    with xr.open_dataset(path) as ds:
        return {
            "X": ds["X"].values,
            "Y": ds["Y"].values,
            "x_true": ds["x_true"].values,
            "y_true": ds["y_true"].values,
            "coefficients": ds["coefficients"].values,
        }


def default_nc_filename(dataset):
    """A descriptive, sortable default filename encoding the generator and its
    key size/seed settings, e.g. "linear_full_n300-p20-o10_seed1.nc" or
    "ode_linear_full_n200-s6-t15_seed1.nc" -- enough to tell datasets apart
    when browsing a directory of them without opening each file.
    """
    meta = dataset.get("metadata", {})
    # structural-regime datasets carry "generator" (the wrapped generate_fn's name)
    # instead of "model"
    parts = [str(meta.get("model", meta.get("generator", "dataset")))]

    structure = meta.get("structure")
    if structure:
        parts.append(str(structure))
    if meta.get("structural_regime_error"):
        parts.append(f"regime{meta.get('regime_fraction', '')}")
    if meta.get("structural_conflicting_models"):
        parts.append("conflict-" + "-".join(meta.get("model_names", [])))

    if "n_states" in meta:
        # ODE/Lorenz-96 datasets also carry n_params (== n_states, from the shared
        # packaging helper) -- check n_states first so these get "s/t" not "p/o".
        n_times = len(meta["t_eval"]) if "t_eval" in meta else "?"
        parts.append(f"n{meta['n_samples']}-s{meta['n_states']}-t{n_times}")
    elif "n_params" in meta:
        parts.append(f"n{meta['n_samples']}-p{meta['n_params']}-o{meta['n_outputs']}")
    elif "n_samples" in meta:
        parts.append(f"n{meta['n_samples']}")

    if meta.get("seed") is not None:
        parts.append(f"seed{meta['seed']}")

    return "_".join(parts) + ".nc"
